import { MAX, YEAR } from "./config";

const ANSDataTemplate = {
  Flt_Sav: {
    type: "-",
    variable: "Flt_Sav",
    label: "연도별 운항시간 목표 절감율",
    value: Array(YEAR).fill(0),
  },
  FTR_DDtotal: {
    type: "-",
    variable: "FTR_DDtotal",
    label: "총 국내선 이륙과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DItotal: {
    type: "-",
    variable: "FTR_DItotal",
    label: "총 국제선 이륙과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_ADtotal: {
    type: "-",
    variable: "FTR_ADtotal",
    label: "총 국내선 착륙과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_AItotal: {
    type: "-",
    variable: "FTR_AItotal",
    label: "총 국제선 착륙과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DRtotal: {
    type: "-",
    variable: "FTR_DRtotal",
    label: "총 국내선 항로과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DIRtotal: {
    type: "-",
    variable: "FTR_DIRtotal",
    label: "총 국제선 이륙-항로과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_AIRtotal: {
    type: "-",
    variable: "FTR_AIRtotal",
    label: "총 국제선 착륙-항로과정 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DDamount: {
    type: "-",
    variable: "CER_DDamount",
    label: "총 국내선 이륙과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIamount: {
    type: "-",
    variable: "CER_DIamount",
    label: "총 국제선 이륙과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_ADamount: {
    type: "-",
    variable: "CER_ADamount",
    label: "총 국내선 착륙과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIamount: {
    type: "-",
    variable: "CER_AIamount",
    label: "총 국제선 착륙과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DRamount: {
    type: "-",
    variable: "CER_DRamount",
    label: "총 국내선 항로과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIRamount: {
    type: "-",
    variable: "CER_DIRamount",
    label: "총 국제선 이륙-항로과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIRamount: {
    type: "-",
    variable: "CER_AIRamount",
    label: "총 국제선 착륙-항로과정 탄소배출 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DDcost: {
    type: "-",
    variable: "CER_DDcost",
    label: "총 국내선 이륙과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIcost: {
    type: "-",
    variable: "CER_DIcost",
    label: "총 국제선 이륙과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_ADcost: {
    type: "-",
    variable: "CER_ADcost",
    label: "총 국내선 착륙과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIcost: {
    type: "-",
    variable: "CER_AIcost",
    label: "총 국제선 착륙과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DRcost: {
    type: "-",
    variable: "CER_DRcost",
    label: "총 국내선 항로과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIRcost: {
    type: "-",
    variable: "CER_DIRcost",
    label: "총 국제선 이륙-항로과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIRcost: {
    type: "-",
    variable: "CER_AIRcost",
    label: "총 국제선 착륙-항로과정 탄소배출 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DDamount: {
    type: "-",
    variable: "FR_DDamount",
    label: "총 국내선 이륙과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIamount: {
    type: "-",
    variable: "FR_DIamount",
    label: "총 국제선 이륙과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_ADamount: {
    type: "-",
    variable: "FR_ADamount",
    label: "총 국내선 착륙과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIamount: {
    type: "-",
    variable: "FR_AIamount",
    label: "총 국제선 착륙과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DRamount: {
    type: "-",
    variable: "FR_DRamount",
    label: "총 국내선 항로과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIRamount: {
    type: "-",
    variable: "FR_DIRamount",
    label: "총 국제선 이륙-항로과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIRamount: {
    type: "-",
    variable: "FR_AIRamount",
    label: "총 국제선 착륙-항로과정 연료 절감량",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DDcost: {
    type: "-",
    variable: "FR_DDcost",
    label: "총 국내선 이륙과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIcost: {
    type: "-",
    variable: "FR_DIcost",
    label: "총 국제선 이륙과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_ADcost: {
    type: "-",
    variable: "FR_ADcost",
    label: "총 국내선 착륙과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIcost: {
    type: "-",
    variable: "FR_AIcost",
    label: "총 국제선 착륙과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DRcost: {
    type: "-",
    variable: "FR_DRcost",
    label: "총 국내선 항로과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIRcost: {
    type: "-",
    variable: "FR_DIRcost",
    label: "총 국제선 이륙-항로과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIRcost: {
    type: "-",
    variable: "FR_AIRcost",
    label: "총 국제선 착륙-항로과정 연료 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_DDcost: {
    type: "-",
    variable: "OPR_DDcost",
    label: "총 국내선 이륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_DIcost: {
    type: "-",
    variable: "OPR_DIcost",
    label: "총 국제선 이륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_ADcost: {
    type: "-",
    variable: "OPR_ADcost",
    label: "총 국내선 착륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_AIcost: {
    type: "-",
    variable: "OPR_ADcost",
    label: "총 국내선 착륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_AIcost_DLY: {
    type: "-",
    variable: "OPR_AIcost_DLY",
    label: "총 국내선 이륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },

  OPR_DIcost_DLY: {
    type: "-",
    variable: "OPR_DIcost_DLY",
    label: "총 국제선 이륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  OPR_ADcost_DLY: {
    type: "-",
    variable: "OPR_ADcost_DLY",
    label: "총 국내선 착륙과정 운항 절감비용",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_DD_Dly: {
    type: "ASSUMPTION",
    variable: "TL_DD_Dly",
    label: "총 국내선 이륙과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_DI_Dly: {
    type: "ASSUMPTION",
    variable: "TL_DI_Dly",
    label: "총 국제선 이륙과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DDamount_byADLY: {
    type: "-",
    variable: "CER_DDamount_byADLY",
    label: "총 국내선 출발과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIamount_byADLY: {
    type: "-",
    variable: "CER_DIamount_byADLY",
    label: "총 국제선 출발과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DDamount_byADLY: {
    type: "-",
    variable: "FR_DDamount_byADLY",
    label: "총 국내선 출발과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIamount_byADLY: {
    type: "-",
    variable: "FR_DIamount_byADLY",
    label: "총 국제선 출발과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DDcost_byADLY: {
    type: "-",
    variable: "CER_DDcost_byADLY",
    label: "총 국내선 출발과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_DIcost_byADLY: {
    type: "-",
    variable: "CER_DIcost_byADLY",
    label: "총 국제선 출발과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DDcost_byADLY: {
    type: "-",
    variable: "FR_DDcost_byADLY",
    label: "총 국내선 출발과정 연료 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_DIcost_byADLY: {
    type: "-",
    variable: "FR_DIcost_byADLY",
    label: "총 국제선 출발과정 연료 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_AD_Dly: {
    type: "ASSUMPTION",
    variable: "TL_AD_Dly",
    label: "총 국내선 도착과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_AI_Dly: {
    type: "ASSUMPTION",
    variable: "TL_AI_Dly",
    label: "총 국제선 도착과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_AI_Dly_LD: {
    type: "ASSUMPTION",
    variable: "TL_AI_Dly_LD",
    label: "총 국제선 도착 착륙과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  TL_AI_Dly_R: {
    type: "ASSUMPTION",
    variable: "TL_AI_Dly_R",
    label: "총 국제선 도착 항로과정 지연 절감시간",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_ADamount_byADLY: {
    type: "-",
    variable: "CER_ADamount_byADLY",
    label: "총 국내선 도착과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIamount_byADLY: {
    type: "-",
    variable: "CER_AIamount_byADLY",
    label: "총 국제선 도착과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AI_Ramount_byADLY: {
    type: "-",
    variable: "CER_AI_Ramount_byADLY",
    label: "총 국내선 도착 항로과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AI_LDamount_byADLY: {
    type: "-",
    variable: "CER_AI_LDamount_byADLY",
    label: "총 국제선 도착 착륙과정 탄소배출 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_ADamount_byADLY: {
    type: "-",
    variable: "FR_ADamount_byADLY",
    label: "총 국내선 착륙과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIamount_byADLY: {
    type: "-",
    variable: "FR_AIamount_byADLY",
    label: "총 국제선 착륙과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AI_LDamount_byADLY: {
    type: "-",
    variable: "FR_AI_LDamount_byADLY",
    label: "총 국내선 도착 착륙과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AI_Ramount_byADLY: {
    type: "-",
    variable: "FR_AI_Ramount_byADLY",
    label: "총 국제선 도착 항로과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_ADcost_byADLY: {
    type: "-",
    variable: "CER_ADcost_byADLY",
    label: "총 국내선 도착과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AIcost_byADLY: {
    type: "-",
    variable: "CER_AIcost_byADLY",
    label: "총 국제선 도착과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AI_Rcost_byADLY: {
    type: "-",
    variable: "CER_AI_Rcost_byADLY",
    label: "총 국내선 도착 항로과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_AI_LDcost_byADLY: {
    type: "-",
    variable: "CER_AI_LDcost_byADLY",
    label: "총 국제선 도착 착륙과정 탄소배출 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_ADcost_byADLY: {
    type: "-",
    variable: "FR_ADcost_byADLY",
    label: "총 국내선 착륙과정 연료 절감비용(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AIcost_byADLY: {
    type: "-",
    variable: "FR_AIcost_byADLY",
    label: "총 국제선 착륙과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AI_LDcost_byADLY: {
    type: "-",
    variable: "FR_AI_LDcost_byADLY",
    label: "총 국내선 도착 착륙과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FR_AI_Rcost_byADLY: {
    type: "-",
    variable: "FR_AI_Rcost_byADLY",
    label: "총 국제선 도착 항로과정 연료 절감량(지연시간 감소)",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  BNF_AD_PSG: {
    type: "-",
    variable: "BNF_AD_PSG",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  BNF_AI_PSG: {
    type: "-",
    variable: "BNF_AI_PSG",
    label: "국제선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  CER_amount_byAFT: {
    type: "-",
    variable: "CER_amount_byAFT",
    label: "총 영공 통과 탄소배출 절감량",
    value: Array(YEAR).fill(0),
  },
  FR_amount_byAFT: {
    type: "-",
    variable: "FR_amount_byAFT",
    label: "총 영공 통과 연료 절감량",
    value: Array(YEAR).fill(0),
  },
  CER_cost_byAFT: {
    type: "-",
    variable: "CER_cost_byAFT",
    label: "총 영공 통과 탄소배출 절감비용",
    value: Array(YEAR).fill(0),
  },
  FR_cost_byAFT: {
    type: "-",
    variable: "FR_cost_byAFT",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  FCE_hour: {
    type: "-",
    variable: "FCE_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  ACE_TO_hour: {
    type: "-",
    variable: "ACE_TO_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  ACE_LD_hour: {
    type: "-",
    variable: "ACE_LD_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  AFE_TO_hour: {
    type: "-",
    variable: "AFE_TO_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  FFE_hour: {
    type: "-",
    variable: "FFE_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  AFE_LD_hour: {
    type: "-",
    variable: "AFE_LD_hour",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  Dly_Sav: {
    type: "-",
    variable: "Dly_Sav",
    label: "총 영공 통과 연료 절감비용",
    value: Array(YEAR).fill(0),
  },
  Avg_AI_Dly_LD: {
    type: "-",
    variable: "Avg_AI_Dly_LD",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Avg_AI_Dly_R: {
    type: "-",
    variable: "Avg_AI_Dly_R",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Time_Pass: {
    type: "-",
    variable: "Time_Pass",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_Pass: {
    type: "-",
    variable: "FTR_Pass",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DDgoal: {
    type: "-",
    variable: "FTR_DDgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_ADgoal: {
    type: "-",
    variable: "FTR_ADgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DRgoal: {
    type: "-",
    variable: "FTR_DRgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DIgoal: {
    type: "-",
    variable: "FTR_DIgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_DIRgoal: {
    type: "-",
    variable: "FTR_DIRgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_AIgoal: {
    type: "-",
    variable: "FTR_AIgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  FTR_AIRgoal: {
    type: "-",
    variable: "FTR_AIRgoal",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Avg_DD_Dly: {
    type: "-",
    variable: "Avg_DD_Dly",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Avg_DI_Dly: {
    type: "-",
    variable: "Avg_DI_Dly",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Avg_AD_Dly: {
    type: "-",
    variable: "Avg_AD_Dly",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  Avg_AI_Dly: {
    type: "-",
    variable: "Avg_AI_Dly",
    label: "국내선 도착 지연시간 감소편익",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  N_DD_Flght: {
    type: "-",
    variable: "N_DD_Flght",
    label: "국내선 출발 총 운항편",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  N_DI_Flght: {
    type: "-",
    variable: "N_DI_Flght",
    label: "국제선 출발 총 운항편",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  N_AD_Flght: {
    type: "-",
    variable: "N_AD_Flght",
    label: "국내선 도착 총 운항편",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  N_AI_Flght: {
    type: "-",
    variable: "N_AI_Flght",
    label: "국제선 도착 총 운항편",
    value: Array.from(Array(MAX), () => new Array(YEAR).fill(0)),
  },
  carbonCredit: {
    type: "-",
    variable: "carbonCredit",
    label: "탄소 배출권 가격",
    value: Array(YEAR).fill(0),
  },
  fuelCredit: {
    type: "-",
    variable: "fuelCredit",
    label: "연료 가격",
    value: Array(YEAR).fill(0),
  },
  OP_DDcost: {
    type: "-",
    variable: "OP_DDcost",
    label: "국내선 출발편 시간당 평균 운항 비용",
    value: Array(YEAR).fill(0),
  },
  OP_DIcost: {
    type: "-",
    variable: "OP_DIcost",
    label: "국제선 출발편 시간당 평균 운항 비용",
    value: Array(YEAR).fill(0),
  },
  OP_ADcost: {
    type: "-",
    variable: "OP_ADcost",
    label: "국내선 도착편 시간당 평균 운항 비용",
    value: Array(YEAR).fill(0),
  },
  OP_AIcost: {
    type: "-",
    variable: "OP_AIcost",
    label: "국제선 도착편 시간당 평균 운항 비용",
    value: Array(YEAR).fill(0),
  },
  N_Pass_Flght: {
    type: "-",
    variable: "N_Pass_Flght",
    label: "총 영공통과 운항편",
    value: Array(YEAR).fill(0),
  },
  Safty_Sav: {
    type: "-",
    variable: "Safty_Sav",
    label: "총 영공통과 운항편",
    value: Array(YEAR).fill(0),
  },
  Safty_cost: {
    type: "-",
    variable: "Safty_cost",
    label: "총 영공통과 운항편",
    value: Array(YEAR).fill(0),
  },
};

export default ANSDataTemplate;
